### PR TITLE
fix: 修复replace会把body上面的属性冲掉的bug

### PR DESCRIPTION
**Pull request by running-grass**

### CODE REVIEW

**Review by roybarber — APPROVED** [review]
This makes this package near perfect. If you have any class names or attributes on your <body> tage then the plugin does not insert the spritesheet

**Comment by Lstmxx** [comment]
> This makes this package near perfect. If you have any class names or attributes on your tage then the plugin does not insert the spritesheet



> _ No description provided. _

谢谢你的PR

**Comment by Lstmxx** [comment]
> This makes this package near perfect. If you have any class names or attributes on your tage then the plugin does not insert the spritesheet

I checked again and no problem.
Bro, thanks for your review.

**Review by Lstmxx — COMMENTED** [review]
thanks for PR and review

**Review by Lstmxx — COMMENTED** [review]
Done.

**Review by Lstmxx — COMMENTED** [review]
image
Done.

**Review by Lstmxx — APPROVED** [review]
image

Done.

**Pull request merged**
